Multiline comments
slime-lang/slime pull request #126
Opened 2017-05-20 15:35 UTC by little-bobby-tables

I've noticed that Slim handles HTML comments (`/!`)  just like verbatim text nodes (`|` and `'`) — complete with interpolation — so I decided to move the common semantics into a `text_block` rule.

The change introduces:
* multiline HTML comments (`/!`)
* text interpolation in HTML comments
* mutlilne code comments (`/`)

What do you think?

2017-05-20 17:18 UTC, Rakoth requested changes
Thanks, @little-bobby-tables, great job refactoring this nasty verbatim_text transform! I left some comments below, please take a look.

2017-05-20 17:18 UTC, Rakoth commented on lib/slime/parser/text_block.ex
> +  def render(lines, decl_indent, trailing_whitespace \\ "") do
May be use `declaration_indent` as variable name? An abbreviation is a bit confusing.

2017-05-20 17:18 UTC, Rakoth commented on lib/slime/parser/text_block.ex
> +      [{indent, _, _} | _] = rest
what about single `'` used for spacing, example similar to one in my work project:
```
p
  '
  span text
  ' .
```
I understand, `span<` could be used here, but it is a valid slim and should be supported (probably should add a test case for it)

2017-05-20 17:18 UTC, Rakoth commented on src/slime_parser.peg.eex
> +tag <- text_item / space? tag_item / blank:(space? &eol);
I think it is better to keep `verbatim_text` separated from `comment`, so here it would be `comment / verbatim_text / ...`

2017-05-21 03:14 UTC, little-bobby-tables commented
Thanks for your comments, @Rakoth! I've added a test case for `'` without content and split `text_item` into `verbatim_text` and `comment`.

However, I've noticed that credo now reports the TextBlock.render function as having excessively high ABC complexity — do you have any ideas on how to refactor it?

2017-05-21 15:31 UTC, Rakoth commented
@little-bobby-tables  Since it is already in a separate module, we could simply extract parts of it into private functions.

2017-05-23 08:19 UTC, Rakoth approved these changes
LGTM 👍

2017-05-23 08:23 UTC, merged