Separate interpolation from verbatim text
slime-lang/slime pull request #130
Opened 2017-06-02 00:42 UTC by little-bobby-tables

This is the last PR I've had in works, it fixes some long-outstanding issues like [this](https://github.com/slime-lang/phoenix_slime/issues/29) and #119.

I've had to change the embedded engines code a bit, I've made sure that the tests are passing but they may not be covering all use cases so feedback on that is highly appreciated.

2017-06-02 19:56 UTC, Rakoth requested changes
😻 Awesome job, @little-bobby-tables!
There is one thing to discuss, I left a comment about interpolations in embedded engines.

2017-06-02 19:56 UTC, Rakoth commented on src/slime_parser.peg.eex
> +text_block_line <- space? text_item*;
Should it be `text_item+`?

2017-06-02 19:56 UTC, Rakoth commented on lib/slime/parser/embedded_engine.ex
> -      %{"engine" => engine, "indent" => indent} when engine in @registered_engines ->
Better to keep this check, it will be easier to add descriptive error in case of invalid engine name

2017-06-02 19:56 UTC, Rakoth commented on lib/slime/parser/embedded_engine.ex
> +    lines = Enum.map(line_contents, &compile/1)
Since engine developer should be aware of interpolation injections into engine body, I think it will be better to pass original list of raw text and interpolations in form of `{:eex, text}` instead of compiled version with interpolations presented as `<%= text %>`. For example in `elixir` engine interpolations should not be converted into `eex` injections at all. Also with this approach there is no need in `compile` here, because the result of embedded engine render will any way go through a compiler later.

2017-06-02 20:10 UTC, Rakoth commented on lib/slime/parser/embedded_engine.ex
> +    lines = Enum.map(line_contents, &compile/1)
example for elixir engine, which now compiles into invalid eex:
```
elixir:
  a = "test"
  b = "b-#{a}"
= b
```

2017-06-03 04:15 UTC, little-bobby-tables commented on src/slime_parser.peg.eex
> +text_block_line <- space? text_item*;
`text_item` only matches a non-empty string, which works well for e.g. `inline_html` where text is mandatory, but needs the optional modifier for empty string consumers like `text_block_line`.

2017-06-03 04:20 UTC, little-bobby-tables commented on lib/slime/parser/embedded_engine.ex
> +    lines = Enum.map(line_contents, &compile/1)
Thanks! I didn't think about that; it certainly makes sense to decide on how to render interpolation on a per engine basis, as your example shows. I've added it as a test case.

On a somewhat unrelated note, this should probably be mentioned in the release notes — it seems to me the [Markdown example](https://github.com/slime-lang/slime#embedded-engines) won't work anymore.

2017-06-03 08:35 UTC, Rakoth approved these changes
There is one more TODO left about separation of dynamic blocks and static text in grammar, we don't need it any more.
👍 LGTM

2017-06-03 08:35 UTC, Rakoth commented on lib/slime/parser/transform.ex
> -  @quote_outside_interpolation_regex ~r/(^|\G)(?:\\.|[^#]|#(?!\{)|(?<pn>#\{(?:[^"}]++|"(?:\\.|[^"#]|#(?!\{)|(?&pn))*")*\}))*?\K"/u
RIP

2017-06-09 17:46 UTC, doomspork commented
:boom:  Thank you @little-bobby-tables and @Rakoth — you guys are awesome 💜

2017-06-09 17:46 UTC, merged