Wrapped multiline attributes
slime-lang/slime pull request #135
Opened 2017-06-23 03:53 UTC by little-bobby-tables

I find it very convenient that Slim allows attributes to be spanned over multiple lines:
```slim
a.link.link--highlighted data-element-class="Object" data-element-id=object.id title="Very long link title" href="#"
```
vs
```slim
a.link.link--highlighted(href="#"
data-element-class="Object"
data-element-id=object.id
title="Very long link title")
```
It'd be nice to have this in Slime.

2017-06-23 06:02 UTC, Rakoth requested changes
All seems fine, but please add end-to-end rendering test

2017-06-23 06:03 UTC, Rakoth commented
this will close #121

2017-06-23 06:33 UTC, Rakoth approved these changes

2017-06-23 06:33 UTC, little-bobby-tables commented
Unfortunately, I haven't found an easy way to support the indented syntax proposed in the issue:
```
input[
  type="text"
  class="form-control"
  name="plop"]
```
due to virtual indents. Making an exception for this structure in the preprocessor might be an acceptable workaround, but it would involve handling some complex cases like the closing bracket followed by inline content, etc.

2017-06-23 07:12 UTC, Rakoth commented
Could we support version with mandatory indent/dedent
```
input[
  a=1
  b=2
]
```
like this?

2017-06-23 07:34 UTC, little-bobby-tables commented
That seems like a nice solution to me, it's more readable than my initial version.

2017-06-23 07:42 UTC, Rakoth commented
@little-bobby-tables could you please check for rendering of nested tag with such attributes
```
p
  input[
    a=1
    b=2
  ]
```
I got a parser error with this example

2017-06-23 07:51 UTC, little-bobby-tables commented
Thanks for catching that, I've added a test case for it.

2017-06-23 08:06 UTC, Rakoth commented
Thanks, @little-bobby-tables! This is awesome!

2017-06-23 08:07 UTC, merged

2017-08-14 18:59 UTC, jeffcole commented
Any chance we could please cut a Hex release that includes this change? 🙇

2017-08-14 19:02 UTC, doomspork commented
Yes @jeffcole!  I will work on that today 👍

2018-01-11 03:33 UTC, jwipeout commented
I am receiving a syntax error when doing this for my boostrap header

```
nav.navbar.navbar-expand-lg.bg-dark
  a.navbar-brand(href="#")
    | Partywave

  button.navbar-toggler[
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  ]
    span.navbar-toggler-icon
```

2018-01-11 06:31 UTC, Rakoth commented
@jwipeout Could you please show what error you seeing and what version of slime you using?