Strip windows line endings
slime-lang/slime pull request #137
Opened 2017-07-07 11:16 UTC by tmbb

All credit goes to sztosz, who fixed this issue originally.
Added test.

Fixes https://github.com/slime-lang/slime/issues/107

2017-07-07 15:26 UTC, Rakoth commented
Hi, @tmbb could you please provide more details about the issue, parser now should handle windows line ending, we have corresponding test case: 

https://github.com/slime-lang/slime/blob/master/test/renderer_test.exs#L91-L93
```
  test "CRLF line endings are converted to LF" do
    assert render("h1\r\n\th2\r\n\t\th3 Hi\r\n") == "<h1><h2><h3>Hi</h3></h2></h1>"
  end
```

2017-07-07 16:18 UTC, tmbb commented
That's strange... I admit I didn't read the whole source, but the master failed in my machine before my fix and started working with my fix. I'll try to figure it out.

2017-07-07 19:43 UTC, tmbb commented
So far:

* That test passes in my machine (i.e. `mix tests` passes)
* The project I'm trying this on, which uses phoenix line, fails with this error:

```
== Compilation error on file lib/talon_blog_demo/talon/views/admin/admin-lte/layout_view.ex ==
** (Slime.TemplateSyntaxError) got FunctionClauseError with message "no function clause matching in String.duplicate/2" while retrieving Exception.message/1 for %Slime.TemplateSyntaxError{column: 0, line: "  head\r", line_number: 3, message: "{:no_match, <<14>>}", source: "INPUT"}
    (slime) lib/slime/parser.ex:27: Slime.Parser.handle_syntax_error/3
    (slime) lib/slime/renderer.ex:17: Slime.Renderer.precompile/1
    (phoenix_slime) lib/phoenix_slime/engine.ex:11: PhoenixSlime.Engine.compile/2
    (phoenix) lib/phoenix/template.ex:378: Phoenix.Template.compile/2
    (phoenix) lib/phoenix/template.ex:186: Phoenix.Template."-MACRO-__before_compile__/2-fun-0-"/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix) expanding macro: Phoenix.Template.__before_compile__/1
    lib/talon_blog_demo/talon/views/admin/admin-lte/layout_view.ex:1: TalonBlogDemo.Admin.AdminLte.Web.LayoutView (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

Not that the final error comes from trying to call String.duplicate(" ", -1), as the error reported at column 0. This is strange (the code doesn't seem to think that an exception at column 0 is possible), but that's not the most important part. The most important part is the syntax error.

I'm not yet deep enough into Slime's source, but the error message ("{:no_match, <<14>>}") seems to indicate an unexpected "\r" character. While initially I attributed this error to the presence of the "\r" character, other files containing the sequence "\r\n" give me no problems. Other files beside this one fail with errors, but the error messages are not as clear, so let's concentrate on this one.

The contents of the file being processed are (`file_path |> File.read! |> inspect`):

```
"doctype html\r\nhtml lang=\"en\"\r\n  head\r\n    meta charset=\"utf-8\"\r\n    meta content=\"IE=edge\" http-equiv=\"X-UA-Compatible\"\r\n    meta content=\"width=device-width, initial-scale=1\" name=\"viewport\"\r\n    meta content=\"\" name=\"description\"\r\n    meta content=\"\" name=\"author\"\r\n    title Talon\r\n    link rel=\"stylesheet\" href=\"\#{static_path(@conn, \"/css/talon/admin-lte/talon.css\")}\"\r\n    link href=\"http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\" rel=\"stylesheet\"\r\n    link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css\"\r\n\r\n  body.sidebar-mini.skin-purple.hold-transition.sidebar-mini\r\n    #delete-form style=\"display: none\"\r\n      = link \"\", to: \"\", method: :delete, data: [confirm: \"are you sure?\"]\r\n    .wrapper\r\n      header.main-header\r\n        a href=\"#\" class=\"logo\"\r\n          span.logo-mini = raw \"<b>T</b>F\"\r\n          span.logo-lg = raw \"<b>T</b>alon\"\r\n    nav.navbar.navbar-static-top\r\n          a.sidebar-toggle href=\"#\" data-toggle=\"offcanvas\" role=\"button\"\r\n            span.sr-only= dgettext \"talon\", \"Toggle navigation\"\r\n          .navbar-custom-menu\r\n            ul.nav.navbar-nav\r\n              li.dropdown.messages-menu\r\n      = render \"sidebar.html\", conn: @conn\r\n      .content-wrapper style=\"min-height: 916px;\"\r\n        / TODO: Move this to a partial\r\n        section.content-header#title_bar style=\"padding-left: 30px;\"\r\n          h1#page_title = index_card_title(@conn)\r\n          ol.breadcrumb\r\n            li\r\n              a href=\"/talon\"\r\n                i.fa.fa-dashboard\r\n                = \"talon\"\r\n        section.content = render @view_module, @view_template, assigns\r\n\r\n      footer.main-footer\r\n\r\n    script src=\"\#{static_path(@conn, \"/js/talon/admin-lte/jquery-2.2.3.min.js\")}\"\r\n    script src=\"\#{static_path(@conn, \"/js/talon/admin-lte/bootstrap.min.js\")}\"\r\n    script src=\"\#{static_path(@conn, \"/js/talon/admin-lte/app.min.js\")}\"\r\n    script src=\"\#{static_path(@conn, \"/js/talon/admin-lte/sweetalert.min.js\")}\"\r\n    script src=\"\#{static_path(@conn, \"/js/app.js\")}\"\r\n"
```

The problem goes away with my fix.
My fix works at the level of the preprocessor.
I don't know what's the relevance of that fact...

I can upload my repo (actually it's a project template by someone else) so that you can test it yourself.

I'm sorry for not being able to be more specific, but try as I may, the fact is that the only thing that fixes this problem is my fix, as illogical as it is.

Thanks for taking the time to work on this issue.

2017-07-08 04:55 UTC, Rakoth commented
I see, the problem is with preprocessor, which inserts virtual symbols of indent `<<14>>` and dedent `<<15>>`, but since preprocessor splits lines by `\n` it insets one of them between `\r` and `\n`.
Could you narrow it down to exact slime template, which causes this problem, so we can add a test case?

2017-07-08 14:03 UTC, tmbb commented
I haven't done any formal analysis to try to find out which templates break Slime on windows, but I've managed to shrink my test case into a possibly minimal example.

It would be interesting to add property testing to Slime. It would have caught this bug in testing (note, that you already had a test case for CRLF problems, but only a slightly more complex template found the error; such more complex templates could be generated as a matter of by property testing frameworks).

If I find the time to learn something like [propcheck](https://github.com/alfert/propcheck) (the custom element generators seem great), I can submit a pull request.

2017-07-09 15:48 UTC, Rakoth requested changes

2017-07-09 15:48 UTC, Rakoth commented on test/renderer_test.exs
> +    example_windows = example_unix |> String.replace("\n", "\r\n")
I am not sure, this test will do the same on windows machine, I think, it is better to state all symbols in a string as in previous test

2017-07-09 15:48 UTC, Rakoth commented on test/renderer_test.exs
> +    assert render(example_unix) == render(example_unix)
better to compare to expected html string (also typo)

2017-07-09 15:50 UTC, Rakoth commented
Ok, I see the problem now, it is with empty line in template.
Sure @tmbb you can send a PR with propcheck 👍

2017-07-09 16:51 UTC, tmbb commented on test/renderer_test.exs
> +    example_windows = example_unix |> String.replace("\n", "\r\n")
It doesn't do the same: it fails on v1.0.0 with an error. Independently of the OS, elixir normalizes the line endings in multiline strings. Line endings will always be "\n", both in windows and linux.

By replacing the linux line endings with windows line endings you mimic the effect of running slime on windows files.

I can compare with the expected output, of course, if you want.

2017-07-09 16:53 UTC, tmbb commented on test/renderer_test.exs
> +    assert render(example_unix) == render(example_unix)
Which typo? I can't find it

2017-07-09 16:54 UTC, tmbb commented on test/renderer_test.exs
> +    assert render(example_unix) == render(example_unix)
Sorry, found it

2017-07-10 03:35 UTC, Rakoth commented on test/renderer_test.exs
> +    example_windows = example_unix |> String.replace("\n", "\r\n")
Nice to know, thanks 👍

2017-07-11 08:11 UTC, Rakoth approved these changes

2017-07-11 08:12 UTC, merged